# Generated by Django 4.1.3 on 2022-11-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.FileField(blank=True, null=True, upload_to='MarketplaceImage')),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, null=True, upload_to='ProductImage')),
                ('status', models.CharField(default='On Going', max_length=30)),
                ('created_date', models.DateField()),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.zipcode')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.marketplace')),
            ],
        ),
    ]
