# Generated by Django 4.1.3 on 2022-11-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=3000, null=True)),
                ('sprit_category', models.CharField(max_length=50, null=True)),
                ('sprit_subcategory', models.CharField(max_length=50, null=True)),
                ('wine_category', models.CharField(max_length=50, null=True)),
                ('wine_subcategory', models.CharField(max_length=50, null=True)),
                ('beer_category', models.CharField(max_length=50, null=True)),
                ('beer_subcategory', models.CharField(max_length=50, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='web.brand')),
            ],
        ),
    ]
