# Generated by Django 4.1.3 on 2022-11-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='web.marketplace'),
        ),
    ]
