# Generated by Django 4.1.3 on 2022-11-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_brand_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
    ]
